###
GET http://localhost:3001/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5ydSIsImNyZWF0ZWRBdCI6IjIwMjItMTEtMDRUMDg6MjU6NDYuMTUwWiIsInVwZGF0ZWRBdCI6IjIwMjItMTEtMDRUMDg6MjU6NDYuMTUwWiIsImlhdCI6MTY2NzU1MDUyMiwiZXhwIjoxNjY3NjUwNTIxfQ.14kYqZMMeQUm-XkbPLdCN0k_C_2JE7DAV3960Bhib8M

###
GET http://localhost:3001/users/1

###
POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "test"
}

###
PUT http://localhost:3001/users/1
Content-Type: application/json

{
    "name": "test name",
    "body": "test body1"
}

###
DELETE http://localhost:3001/users/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6bnVsbCwiZW1haWwiOiJ0ZXN0QG1haWwiLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTAxVDIyOjI1OjAyLjA2OVoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTAxVDIyOjI1OjAyLjA2OVoiLCJpYXQiOjE2NTQxMjU5OTcsImV4cCI6MTY1NDI5ODc5N30.WCuxvYXIbyRMrxn4gT81Sy1L4qvkt1FtJ2GeHm5qKG8
